spring:
  config:
    activate:
      on-profile: prod
  datasource:
    url: jdbc:mysql://34.64.167.130:3306/timedeal?serverTimezone=UTC&characterEncoding=UTF-8
    username: root
    password: 1234
    driver-class-name: com.mysql.cj.jdbc.Driver
  redis:
    host: 34.22.83.173
    port: 6379
  session:
    store-type: redis
  jpa:
    database: mysql
    open-in-view: false
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate.dialect: org.hibernate.dialect.MySQL8Dialect
      hibernate.format_sql: true
      hibernate.show_sql: true
      hibernate.use_sql_comments: true
      hibernate.default_batch_fetch_size: 150
    defer-datasource-initialization: true
  sql:
    init:
      mode: always

info:
  app:
    name: timedeal-actuator
    company: dongmin.na

management:
  info:
    env:
      enabled: true
    java:
      enabled: true
    os:
      enabled: true
  endpoint:
    health:
      show-details: always
  endpoints:
    web:
      exposure:
        include: "*"

server:
  tomcat:
    mbeanregistry:
      enabled: true
  servlet:
    session:
      timeout: 1800
