spring:
  config:
    activate:
      on-profile: local
  datasource:
#    url: jdbc:h2:tcp://localhost/~/timedeallocal
    url: jdbc:mysql://localhost:3306/timedeal?serverTimezone=UTC&characterEncoding=UTF-8
#    username: sa
    username: root
#    password: 1234
    password: 1234
#    driver-class-name: org.h2.Driver
    driver-class-name: com.mysql.cj.jdbc.Driver
    hikari:
      maximum-pool-size: 20
      idle-timeout: 100
      max-lifetime: 100
  redis:
    host: localhost
    port: 6379
  session:
    store-type: redis
  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate.format_sql: true
      hibernate.show_sql: true
      hibernate.use_sql_comments: true
      hibernate.default_batch_fetch_size: 150

server:
  servlet:
    session:
      timeout: 1800


#  jdbc:h2:~/timedeallocal
#  jdbc:h2:tcp://localhost/~/timedeallocal
logging:
  level:
    org.hibernate.type.descriptor.sql: trace
    org.hibernate.sql: INFO
    com.zaxxer.hikari.HikariConfig: DEBUG
    com.zaxxer.hikari: TRACE

