spring:
  config:
    activate:
      on-profile: dev
  datasource:
    url: jdbc:mysql://localhost:3306/timedeal?serverTimezone=UTC&characterEncoding=UTF-8
    username: root
    password: 1234
    driver-class-name: com.mysql.cj.jdbc.Driver
  redis:
    host: localhost
    port: 6379
  session:
    store-type: redis
  jpa:
    database: mysql
    open-in-view: false
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate.dialect: org.hibernate.dialect.MySQL8Dialect
#      hibernate.format_sql: true
      hibernate.show_sql: true
#      hibernate.use_sql_comments: true
      hibernate.default_batch_fetch_size: 150
    defer-datasource-initialization: true
  sql:
    init:
      mode: always
  data:
    mongodb:
      uri: mongodb://localhost:27017/timedeal_product

server:
  servlet:
    session:
      timeout: 1800

logging:
  level:
    org:
      hibernate:
        type:
          descriptor:
            sql: trace
